plugins {
    id 'java'
}

group = 'speculatingwook.spring'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.springframework:spring-context:6.1.14"
    implementation "jakarta.annotation:jakarta.annotation-api:2.1.1"
    implementation "org.aspectj:aspectjweaver:1.9.19"
    implementation "org.springframework:spring-tx:6.1.14"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}